package com.krogerqa.utils;

import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;

public class ExcelUtils {
    public static final String SNAP_EBT_PIN_NUMBER = "0005";
    public static final String INSTACART_SCENARIO_TC_12863 = "INSTACART_SCENARIO_TC_12863";
    public static final String PCL_OVERSIZE_TC_12187 = "PCL_OVERSIZE_TC_12187";
    public static final String MULTIPLE_ORDER_TROLLEY_BAG = "MULTIPLE_ORDER_TROLLEY_BAG";
    public static final String BAG_MAP = "BAG_MAP";
    public static final String BYOB_PCL_TC_8528 = "BYOB_PCL_TC_8528";
    public static final String BYOB_PCL_TC_7455 = "BYOB_PCL_TC_7455";
    public static final String BYOB_PCL_TC_7471 = "BYOB_PCL_TC_7471";
    public static final String BYOB_PCL_TC_7467 = "BYOB_PCL_TC_7467";
    public static final String BYOB_PCL_TC_7468 = "BYOB_PCL_TC_7468";
    public static final String BYOB_PCL_TC_7461 = "BYOB_PCL_TC_7461";
    public static final String BYOB_PCL_TC_7465 = "BYOB_PCL_TC_7465";
    public static final String BYOB_PCL_TC_7459 = "BYOB_PCL_TC_7459";
    public static final String BYOB_PCL_TC_7459_1 = "BYOB_PCL_TC_7459_1";
    public static final String BYOB_PCL_TC_7459_2 = "BYOB_PCL_TC_7459_2";
    public static final String BYOB_PCL_TC_7452 = "BYOB_PCL_TC_7452";
    public static final String BYOB_PCL_TC_8529 = "BYOB_PCL_TC_8529";
    public static final String BYOB_PCL_TC_8529_1 = "BYOB_PCL_TC_8529_1";
    public static final String BYOB_PCL_TC_7454 = "BYOB_PCL_TC_7454";
    public static final String DYNAMIC_BATCH_PCL_TC_12735 = "DYNAMIC_BATCH_PCL_TC_12735";
    public static final String DYNAMIC_BATCH_PCL_TC_12731 = "DYNAMIC_BATCH_PCL_TC_12731";
    public static final String DYNAMIC_BATCH_PCL_TC_12731_1 = "DYNAMIC_BATCH_PCL_TC_12731_1";
    public static final String DYNAMIC_BATCH_TC_12727_1 = "DYNAMIC_BATCH_TC_12727_1";
    public static final String DYNAMIC_BATCH_TC_12727_2 = "DYNAMIC_BATCH_TC_12727_2";
    public static final String BULK_STAGING_TC_11730 = "BULK_STAGING_TC_11730";
    public static final String PCL_SCENARIO_TC_5500 = "PCL_SCENARIO_TC_5500";
    public static final String MAFP_CIAO_SCENARIO_TC_10463 = "MAFP_CIAO_SCENARIO_TC_10463";
    public static final String PCL_OVERSIZE_TC_12172 = "PCL_OVERSIZE_TC_12172";
    public static final String MAFP_CIAO_SCENARIO_TC_10460 = "MAFP_CIAO_SCENARIO_TC_10460";
    public static final String MAFP_CIAO_SCENARIO_TC_10435 = "MAFP_CIAO_SCENARIO_TC_10435";
    public static final String THIRD_ORDER = "THIRD_ORDER";
    public static final String PCL_BYOB_TC_7463 = "PCL_BYOB_TC_7463";
    public static final String BULK_STAGING_TC_11731 = "BULK_STAGING_TC_11731";
    public static final String MAFP_CIAO_SCENARIO_TC_10422 = "MAFP_CIAO_SCENARIO_TC_10422";
    public static final String MAFP_CIAO_SCENARIO_TC_10432 = "MAFP_CIAO_SCENARIO_TC_10432";
    public static final String MAFP_CIAO_SCENARIO_TC_10414 = "MAFP_CIAO_SCENARIO_TC_10414";
    public static final String PCL_OVERSIZE_TC_12199 = "PCL_OVERSIZE_TC_12199";
    public static final String MAFP_CIAO_SCENARIO_TC_10447 = "MAFP_CIAO_SCENARIO_TC_10447";
    public static final String PICK_MULTIPLE_QTY_SERVICE_COUNTER_ITEM = "PICK_MULTIPLE_QTY_SERVICE_COUNTER_ITEM";
    public static final String SINGLE_THREAD_PCL_TC_9013 = "SINGLE_THREAD_PCL_TC_9013";
    public static final String BULK_STAGING_TC_11752 = "BULK_STAGING_TC_11752";
    public static final String BULK_STAGING_TC_11720 = "BULK_STAGING_TC_11720";
    public static final String BULK_STAGING_TC_11755 = "BULK_STAGING_TC_11755";
    public static final String BULK_STAGING_TC_11755_1 = "BULK_STAGING_TC_11755_1";
    public static final String BULK_STAGING_TC_11755_2 = "BULK_STAGING_TC_11755_2";
    public static final String BULK_STAGING_TC_11718 = "BULK_STAGING_TC_11718";
    public static final String ANCHOR_STAGING_TC_5314 = "ANCHOR_STAGING_TC_5314";
    public static final String PCL_OVERSIZE_TC_12248 = "PCL_OVERSIZE_TC_12248";
    public static final String IS_MULTIPLE_TEMP_CONTAINER_ITEM_MOVEMENT = "IS_MULTIPLE_TEMP_CONTAINER_ITEM_MOVEMENT";
    public static final String NO_ITEM_MOVEMENT_CONTAINER = "NO_ITEM_MOVEMENT_CONTAINER";
    public static final String IS_MULTIPLE_CONTAINER_ITEM_MOVEMENT = "IS_MULTIPLE_CONTAINER_ITEM_MOVEMENT";
    public static final String SINGLE_TROLLEY = "SINGLE_TROLLEY";
    public static final String MULTIPLE_ORDER_ROMB = "MULTIPLE_ORDER_ROMB";
    public static final String MULTIPLE_ORDER_BATCH = "MULTIPLE_ORDER_BATCH";
    public static final String EB_PCL_TC_10903 = "EB_PCL_TC_10903";
    public static final String EB_PCL_TC_10902 = "EB_PCL_TC_10902";
    public static final String EB_PCL_TC_10902_1 = "EB_PCL_TC_10902_1";
    public static final String EB_PCL_TC_10902_2 = "EB_PCL_TC_10902_2";
    public static final String EB_PCL_TC_10903_2 = "EB_PCL_TC_10903_2";
    public static final String HT_DB_MULTITHREAD_TC_14379 = "HT_DB_MULTITHREAD_TC_14379";
    public static final String HT_DB_MULTITHREAD_TC_14379_1 = "HT_DB_MULTITHREAD_TC_14379_1";
    public static final String PRE_WEIGHED = "PRE_WEIGHED";
    public static final String PRE_WEIGHED_CONTAINER = "PRE_WEIGHED_CONTAINER";
    public static final String PCL_TOTE_MAP = "PCL_TOTE_MAP";
    public static final String SINGLE_THREAD_PCL_TC_9014 = "SINGLE_THREAD_PCL_TC_9014";
    public static final String SINGLE_THREAD_PCL_TC_9015 = "SINGLE_THREAD_PCL_TC_9015";
    public static final String EB_PCL_TC_10903_1 = "EB_PCL_TC_10903_1";
    public static final String COLLAPSE_AM_RE_OSFR = "COLLAPSE_AM_RE_OSFR";
    public static final String SINGLE_THREAD_PCL_TC_9873 = "SINGLE_THREAD_PCL_TC_9873";
    public static final String SINGLE_THREAD_PCL_TC_9873_1 = "SINGLE_THREAD_PCL_TC_9873_1";
    public static final String SINGLE_THREAD_PCL_TC_9873_2 = "SINGLE_THREAD_PCL_TC_9873_2";
    public static final String ENHANCED_BATCHING_MAP_OOS = "ENHANCED_BATCHING_MAP_OOS";
    public static final String SINGLE_THREAD_PCL_TC_9003 = "SINGLE_THREAD_PCL_TC_9003";
    public static final String SINGLE_THREAD_PCL_TC_9011 = "SINGLE_THREAD_PCL_TC_9011";
    public static final String SINGLE_THREAD_PCL_TC_9009 = "SINGLE_THREAD_PCL_TC_9009";
    public static final String SINGLE_THREAD_PCL_TC_9005 = "SINGLE_THREAD_PCL_TC_9005";
    public static final String SINGLE_THREAD_PCL_TC_9714 = "SINGLE_THREAD_PCL_TC_9714";
    public static final String SINGLE_THREAD_PCL_TC_9719 = "SINGLE_THREAD_PCL_TC_9719";
    public static final String SINGLE_THREAD_PCL_TC_8729 = "SINGLE_THREAD_PCL_TC_8729";
    public static final String IS_MULTIPLE_ORDER_PCL_OS = "IS_MULTIPLE_ORDER_PCL_OS";
    public static final String PCL_OS_PROD_DEFECT_MULTI_ORDERS = "PCL_OS_PROD_DEFECT_MULTI_ORDERS";
    public static final String PCL_OS_PROD_DEFECT_MULTI_ORDER_1 = "PCL_OS_PROD_DEFECT_MULTI_ORDER_1";
    public static final String SINGLE_THREAD_PCL_TC_9001 = "SINGLE_THREAD_PCL_TC_9001";
    public static final String SINGLE_THREAD_PCL_TC_9001_1 = "SINGLE_THREAD_PCL_TC_9001_1";
    public static final String SINGLE_THREAD_PCL_TC_9644 = "SINGLE_THREAD_PCL_TC_9644";
    public static final String PCL_OVERSIZE_TC_12140 = "PCL_OVERSIZE_TC_12140";
    public static final String PCL_OVERSIZE_TC_12140_1 = "PCL_OVERSIZE_TC_12140_1";
    public static final String PCL_OVERSIZE_TC_12055 = "PCL_OVERSIZE_TC_12055";
    public static final String PCL_OVERSIZE_TC_12130 = "PCL_OVERSIZE_TC_12130";
    public static final String PCL_OVERSIZE_TC_12133 = "PCL_OVERSIZE_TC_12133";
    public static final String PCL_OVERSIZE_TC_12241 = "PCL_OVERSIZE_TC_12241";
    public static final String PCL_OVERSIZE_TC_12139 = "PCL_OVERSIZE_TC_12139";
    public static final String PCL_OVERSIZE_TC_12088 = "PCL_OVERSIZE_TC_12088";
    public static final String PCL_OVERSIZE_TC_12088_1 = "PCL_OVERSIZE_TC_12088_1";
    public static final String PCL_OVERSIZE_TC_12186 = "PCL_OVERSIZE_TC_12186";
    public static final String PCL_OVERSIZE_TC_12184 = "PCL_OVERSIZE_TC_12184";
    public static final String PCL_OVERSIZE_TC_12218 = "PCL_OVERSIZE_TC_12218";
    public static final String PCL_OVERSIZE_TC_12211 = "PCL_OVERSIZE_TC_12211";
    public static final String PCL_OVERSIZE_TC_12220 = "PCL_OVERSIZE_TC_12220";
    public static final String PCL_OVERSIZE_TC_12222 = "PCL_OVERSIZE_TC_12222";
    public static final String PCL_OVERSIZE_TC_12217 = "PCL_OVERSIZE_TC_12217";
    public static final String PCL_OVERSIZE_TC_12216 = "PCL_OVERSIZE_TC_12216";
    public static final String PCL_OVERSIZE_TC_12221 = "PCL_OVERSIZE_TC_12221";
    public static final String PCL_OVERSIZE_TC_12225 = "PCL_OVERSIZE_TC_12225";
    public static final String PCL_OVERSIZE_TC_12166 = "PCL_OVERSIZE_TC_12166";
    public static final String PCL_OVERSIZE_TC_12215 = "PCL_OVERSIZE_TC_12215";
    public static final String PCL_OVERSIZE_TC_12171 = "PCL_OVERSIZE_TC_12171";
    public static final String PCL_OVERSIZE_TC_12168 = "PCL_OVERSIZE_TC_12168";
    public static final String PCL_OVERSIZE_TC_12135 = "PCL_OVERSIZE_TC_12135";
    public static final String PCL_OVERSIZE_TC_12135_1 = "PCL_OVERSIZE_TC_12135_1";
    public static final String PCL_OVERSIZE_TC_12135_1_1 = "PCL_OVERSIZE_TC_12135_1_1";
    public static final String PCL_OVERSIZE_TC_12136 = "PCL_OVERSIZE_TC_12136";
    public static final String PCL_OVERSIZE_TC_12137 = "PCL_OVERSIZE_TC_12137";
    public static final String PCL_OVERSIZE_TC_12132 = "PCL_OVERSIZE_TC_12132";
    public static final String PCL_OVERSIZE_TC_12132_1 = "PCL_OVERSIZE_TC_12132_1";
    public static final String PCL_OVERSIZE_TC_12132_2 = "PCL_OVERSIZE_TC_12132_2";
    public static final String PCL_OVERSIZE_TC_12132_3 = "PCL_OVERSIZE_TC_12132_3";
    public static final String PCL_OVERSIZE_TC_12239 = "PCL_OVERSIZE_TC_12239";
    public static final String PCL_OVERSIZE_TC_12170 = "PCL_OVERSIZE_TC_12170";
    public static final String PCL_OVERSIZE_TC_12236 = "PCL_OVERSIZE_TC_12236";
    public static final String SINGLE_THREAD_PCL_TC_9010 = "SINGLE_THREAD_PCL_TC_9010";
    public static final String SINGLE_THREAD_PCL_TC_9716 = "SINGLE_THREAD_PCL_TC_9716";
    public static final String SINGLE_THREAD_PCL_TC_9004 = "SINGLE_THREAD_PCL_TC_9004";
    public static final String IS_RANDOM_WEIGHT_ITEM = "IS_RANDOM_WEIGHT_ITEM";
    public static final String SINGLE_THREAD_PCL_TC_9006 = "SINGLE_THREAD_PCL_TC_9006";
    public static final String BULK_STAGING_TC_11719 = "BULK_STAGING_TC_11719";
    public static final String PCL_SCENARIO_TC_5499 = "PCL_SCENARIO_TC_5499";
    public static final String MOVE_TO_SAME_ITEM_CONTAINER = "MOVE_TO_SAME_ITEM_CONTAINER";
    public static final String ITEM_MOVEMENT_FROM_PICKED_TO_STAGED = "ITEM_MOVEMENT_FROM_PICKED_TO_STAGED";
    public static final String SINGLE_THREAD_PCL_TC_9917 = "SINGLE_THREAD_PCL_TC_9917";
    public static final String DYNAMIC_BATCH_PCL_TC_9511 = "DYNAMIC_BATCH_PCL_TC_9511";
    public static final String DYNAMIC_BATCH_PCL_ANCHOR_9511 = "DYNAMIC_BATCH_PCL_ANCHOR_9511";
    public static final String EB_PCL_RUSH_ORDER_TC_10878 = "EB_PCL_RUSH_ORDER_TC_10878";
    public static final String EB_PCL_RUSH_ORDER_TC_10878_1 = "EB_PCL_RUSH_ORDER_TC_10878_1";
    public static final String SINGLE_THREAD_PCL_TC_8730 = "SINGLE_THREAD_PCL_TC_8730";
    public static final String SINGLE_THREAD_PCL_TC_9724 = "SINGLE_THREAD_PCL_TC_9724";
    public static final String SINGLE_THREAD_PCL_TC_9720 = "SINGLE_THREAD_PCL_TC_9720";
    public static final String SINGLE_THREAD_PCL_TC_9720_1 = "SINGLE_THREAD_PCL_TC_9720_1";
    public static final String SINGLE_THREAD_PCL_TC_9717 = "SINGLE_THREAD_PCL_TC_9717";
    public static final String SINGLE_THREAD_PCL_TC_9008 = "SINGLE_THREAD_PCL_TC_9008";
    public static final String SINGLE_THREAD_PCL_TC_9012 = "SINGLE_THREAD_PCL_TC_9012";
    public static final String SINGLE_THREAD_PCL_TC_8731 = "SINGLE_THREAD_PCL_TC_8731";
    public static final String SINGLE_THREAD_PCL_TC_8731_1 = "SINGLE_THREAD_PCL_TC_8731_1";
    public static final String SINGLE_THREAD_PCL_TC_9002 = "SINGLE_THREAD_PCL_TC_9002";
    public static final String BULK_STAGING_TC_11746 = "BULK_STAGING_TC_11746";
    public static final String EB_NON_PCL_TC_10940 = "EB_NON_PCL_TC_10940";
    public static final String MULTIPLE_TEMP_COLLAPSE = "MULTIPLE_TEMP_COLLAPSE";
    public static final String EB_PCL_TC_10945 = "EB_PCL_TC_10945";
    public static final String EB_PCL_TC_10943 = "EB_PCL_TC_10943";
    public static final String PCL_BYOB_TC_7451 = "PCL_BYOB_TC_7451";
    public static final String EB_PCL_TC_10943_1 = "EB_PCL_TC_10943_1";
    public static final String EB_PCL_TC_10943_1_1 = "EB_PCL_TC_10943_1_1";
    public static final String EB_PCL_TC_10946 = "EB_PCL_TC_10946";
    public static final String EB_PCL_BYOB_TC_10912 = "EB_PCL_BYOB_TC_10912";
    public static final String DYNAMIC_BATCH_PCL_TC_9512 = "DYNAMIC_BATCH_PCL_TC_9512";
    public static final String EB_PCL_TC_10907 = "EB_PCL_TC_10907";
    public static final String EB_PCL_TC_10907_1 = "EB_PCL_TC_10907_1";
    public static final String ACCEPT_BAG_FEES_AFTER_PICKING = "ACCEPT_BAG_FEES_AFTER_PICKING";
    public static final String SINGLE_THREAD_PCL_TC_9007 = "SINGLE_THREAD_PCL_TC_9007";
    public static final String SINGLE_THREAD_PCL_TC_9713 = "SINGLE_THREAD_PCL_TC_9713";
    public static final String SINGLE_THREAD_PCL_TC_9000 = "SINGLE_THREAD_PCL_TC_9000";
    public static final String SINGLE_THREAD_PCL_TC_8813 = "SINGLE_THREAD_PCL_TC_8813";
    public static final String DYNAMIC_BATCH_PCL_TC_9499 = "DYNAMIC_BATCH_PCL_TC_9499";
    public static final String DYNAMIC_BATCH_PCL_BYOB_TC_9513 = "DYNAMIC_BATCH_PCL_BYOB_TC_9513";
    public static final String REJECT_BAG_FEES = "REJECT_BAG_FEES";
    public static final String ACCEPT_BAG_FEES = "ACCEPT_BAG_FEES";
    public static final String IS_BYOB_FLOW = "IS_BYOB_FLOW";
    public static final String CHANGE_BAG_PREF = "CHANGE_BAG_PREF";
    public static final String IS_AMBIENT_CONTAINER = "IS_AMBIENT_CONTAINER";
    public static final String EB_PCL_SHIPT_ON_PREM_TC_10937_1 = "EB_PCL_SHIPT_ON_PREM_TC_10937_1";
    public static final String EB_PCL_SHIPT_ON_PREM_TC_10937_2 = "EB_PCL_SHIPT_ON_PREM_TC_10937_2";
    public static final String EB_PCL_SHIPT_AZURE_TC_10936_1 = "EB_PCL_SHIPT_AZURE_TC_10936_1";
    public static final String EB_PCL_SHIPT_AZURE_TC_10936_2 = "EB_PCL_SHIPT_AZURE_TC_10936_2";
    public static final String IS_DELIVERY_SHIPT_PIF_ORDER = "IS_DELIVERY_SHIPT_PIF_ORDER";
    public static final String IS_DELIVERY_SHIPT_PIF_CANCEL_ORDER = "IS_DELIVERY_SHIPT_PIF_CANCEL_ORDER";
    public static final String PICK_SERVICE_COUNTER_ITEM = "PICK_SERVICE_COUNTER_ITEM";
    public static final String COURIER_SERVICES_9601 = "COURIER_SERVICES_9601";
    public static final String MAFP_CIAO_SCENARIO_TC_10434 = "MAFP_CIAO_SCENARIO_TC_10434";
    public static final String MAFP_CIAO_SCENARIO_TC_10434_1 = "MAFP_CIAO_SCENARIO_TC_10434_1";
    public static final String MAFP_CIAO_SCENARIO_TC_10434_1_1 = "MAFP_CIAO_SCENARIO_TC_10434_1_1";
    public static final String MAFP_CIAO_SCENARIO_TC_10459 = "MAFP_CIAO_SCENARIO_TC_10459";
    public static final String MAFP_CIAO_SCENARIO_TC_10459_1 = "MAFP_CIAO_SCENARIO_TC_10459_1";
    public static final String MAFP_CIAO_SCENARIO_TC_10461 = "MAFP_CIAO_SCENARIO_TC_10461";
    public static final String MAFP_CIAO_SCENARIO_TC_10461_1 = "MAFP_CIAO_SCENARIO_TC_10461_1";
    public static final String MAFP_CIAO_SCENARIO_TC_10462 = "MAFP_CIAO_SCENARIO_TC_10462";
    public static final String MAFP_CIAO_SCENARIO_TC_10464 = "MAFP_CIAO_SCENARIO_TC_10464";
    public static final String MAFP_CIAO_SCENARIO_TC_10433 = "MAFP_CIAO_SCENARIO_TC_10433";
    public static final String MAFP_CIAO_SCENARIO_TC_10423 = "MAFP_CIAO_SCENARIO_TC_10423";
    public static final String MAFP_CIAO_SCENARIO_TC_10443 = "MAFP_CIAO_SCENARIO_TC_10443";
    public static final String IS_MULTIPLE_ORDER_STAGING = "IS_MULTIPLE_ORDER_STAGING";
    public static final String DYNAMIC_BATCH_REUSE_TC_9503_1 = "DYNAMIC_BATCH_REUSE_TC_9503_1";
    public static final String DYNAMIC_BATCH_REUSE_TC_9503 = "DYNAMIC_BATCH_REUSE_TC_9503";
    public static final String DYNAMIC_BATCH_IM_PCL_TC_9503 = "DYNAMIC_BATCH_IM_PCL_TC_9503";
    public static final String DYNAMIC_BATCH_IM_PCL_TC_9502 = "DYNAMIC_BATCH_IM_PCL_TC_9502";
    public static final String DYNAMIC_BATCH_IM_PCL_TC_9511 = "DYNAMIC_BATCH_IM_PCL_TC_9511";
    public static final String DYNAMIC_BATCH_IM_PCL_TC_9512 = "DYNAMIC_BATCH_IM_PCL_TC_9512";
    public static final String ROMB_SCENARIO_TC_7142 = "ROMB_SCENARIO_TC_7142";
    public static final String ROMB_SCENARIO_TC_7142_1 = "ROMB_SCENARIO_TC_7142_1";
    public static final String ROMB_SCENARIO_TC_7142_2 = "ROMB_SCENARIO_TC_7142_2";
    public static final String ROMB_SCENARIO_TC_7142_3 = "ROMB_SCENARIO_TC_7142_3";
    public static final String IS_MULTIPLE_OS_ORDER = "IS_MULTIPLE_OS_ORDER";
    public static final String EB_PCL_TC_10947 = "EB_PCL_TC_10947";
    public static final String BULK_STAGING_TC_11748 = "BULK_STAGING_TC_11748";
    public static final String BULK_STAGING_TC_11732 = "BULK_STAGING_TC_11732";
    public static final String IS_COLLAPSE_TEMP_AMRE_ORDER = "IS_COLLAPSE_TEMP_AMRE_ORDER";
    public static final String ROMB_SCENARIO_TC_7123 = "ROMB_SCENARIO_TC_7123";
    public static final String ROMB_SCENARIO_TC_7123_1 = "ROMB_SCENARIO_TC_7123_1";
    public static final String IS_MULTIPLE_SLOT_RUSH_ORDER = "IS_MULTIPLE_SLOT_RUSH_ORDER";
    public static final String ROMB = "ROMB";
    public static final String ITEM_COUNT = "ITEM_COUNT";
    public static final String ORDER_SLOT = "ORDER_SLOT";
    public static final String MAFP_NOT_READY_FOR_ORDER_ADJUSTMENT_WEIGHT = "MAFP_NOT_READY_FOR_ORDER_ADJUSTMENT_WEIGHT";
    public static final String IS_MULTIPLE_ORDER_DYNAMIC_BATCHING = "IS_MULTIPLE_ORDER_DYNAMIC_BATCHING";
    public static final String PICKED_CONTAINER_MAP = "PICKED_CONTAINER_MAP";
    public static final String GRANULAR_SCENARIO_TC_5004 = "GRANULAR_SCENARIO_TC_5004";
    public static final String ANCHOR_SCENARIO_TC_5308 = "ANCHOR_SCENARIO_TC_5308";
    public static final String CONTAINER_STAGING_ZONE_MAP = "CONTAINER_STAGING_ZONE_MAP";
    public static final String IS_CUE_STAGING_ZONE_VALIDATION = "IS_CUE_STAGING_ZONE_VALIDATION";
    public static final String IS_INVALID_STAGING_LOCATION_VALIDATION = "IS_INVALID_STAGING_LOCATION_VALIDATION";
    public static final String DYNAMIC_BATCH_TC_5583_1 = "DYNAMIC_BATCH_TC_5583_1";
    public static final String DYNAMIC_BATCH_TC_5583_2 = "DYNAMIC_BATCH_TC_5583_2";
    public static final String DYNAMIC_BATCH_TC_5583_3 = "DYNAMIC_BATCH_TC_5583_3";
    public static final String ANCHOR_SCENARIO_TC_5318 = "ANCHOR_SCENARIO_TC_5318";
    public static final String ANCHOR_SCENARIO_TC_5310 = "ANCHOR_SCENARIO_TC_5310";
    public static final String ANCHOR_SCENARIO_TC_5310_1 = "ANCHOR_SCENARIO_TC_5310_1";
    public static final String IS_ANCHOR_STAGING_SINGLE_TROLLEY_PICKING = "IS_ANCHOR_STAGING_SINGLE_TROLLEY_PICKING";
    public static final String KROGER_FEDERATION = "Kroger_Federation";
    public static final String PCL_SCENARIO_TC_4509 = "PCL_SCENARIO_TC_4509";
    public static final String PCL_SCENARIO_TC_4529 = "PCL_SCENARIO_TC_4529";
    public static final String PCL_SCENARIO_TC_4529_1 = "PCL_SCENARIO_TC_4529_1";
    public static final String FLEX_SCENARIO_TC_4868 = "FLEX_SCENARIO_TC_4868";
    public static final String PCL_SCENARIO_TC_5506 = "PCL_SCENARIO_TC_5506";
    public static final String PCL_SCENARIO_TC_4543 = "PCL_SCENARIO_TC_4543";
    public static final String PCL_SCENARIO_TC_4474 = "PCL_SCENARIO_TC_4474";
    public static final String PCL_SCENARIO_TC_4459 = "PCL_SCENARIO_TC_4459";
    public static final String PCL_SCENARIO_TC_5492 = "PCL_SCENARIO_TC_5492";
    public static final String PCL_SCENARIO_TC_5493 = "PCL_SCENARIO_TC_5493";
    public static final String SUBSTITUTION = "SUBSTITUTION";
    public static final String TAKE_OVER_WITH_ITEM_MOVEMENT = "TAKE_OVER_WITH_ITEM_MOVEMENT";
    public static final String ORDER_NUMBER = "ORDER_NUMBER";
    public static final String VERSION_KEY = "VERSION_KEY";
    public static final String ACTIVATE_RESPONSE_VERSION_KEY = "ACTIVATE_RESPONSE_VERSION_KEY";
    public static final String STORE_ID = "STORE_ID";
    public static final String IS_EBT = "IsEBT";
    public static final String IS_SNAP_EBT = "IS_SNAP_EBT";
    public static final String STORE_BANNER = "STORE_BANNER";
    public static final String BANNER_HARRIS_TEETER = "Harris Teeter";
    public static final String BATCHING_SINGLE_TROLLEY_SISTER_STORE = "BATCHING_SINGLE_TROLLEY_SISTER_STORE";
    public static final String BATCH_ORDER = "BATCH_ORDER";
    public static final String IS_MODIFY_ORDER = "IS_MODIFY_ORDER";
    public static final String SUBSTITUTED_ITEM_UPC = "SUBSTITUTED_ITEM_UPC";
    public static final String MULTIPLE_SUBS = "MULTIPLE_SUBS";
    public static final String MULTIPLE_SUBS_UPC = "MULTIPLE_SUBS_UPC";
    public static final String REJECTED_ITEM_PCL_CONTAINER = "REJECTED_ITEM_PCL_CONTAINER";
    public static final String COUPON_TOTAL = "COUPON_TOTAL";
    public static final String IS_CARRYOVER = "IS_CARRYOVER";
    public static final String ANCHOR_SCENARIO_TC_5316 = "ANCHOR_SCENARIO_TC_5316";
    public static final String IS_DYNAMIC_BATCHING = "IS_DYNAMIC_BATCHING";
    public static final String HARRIS_TEETER_DYB = "HARRIS_TEETER_DYB";
    public static final String DB_SINGLE_THREAD_12729 = "DB_SINGLE_THREAD_12729";
    public static final String HEADS_UP_SCREEN = "HEADS_UP_SCREEN";
    public static final String DB_EXPRESS_ORDER_TC_14051 = "DB_EXPRESS_ORDER_TC_14051";
    public static final String DB_SINGLE_THREAD_12729_1 = "DB_SINGLE_THREAD_12729_1";
    public static final String DB_SINGLE_THREAD_12729_1_1 = "DB_SINGLE_THREAD_12729_1_1";
    public static final String BYOB_ALL_COLLAPSE = "BYOB_ALL_COLLAPSE";
    public static final String KROGER_SAVINGS = "KROGER_SAVINGS";
    public static final String CIAO_AGE_CHECK = "CIAO_AGE_CHECK";
    public static final String USER_EMAIL = "USER_EMAIL";
    public static final String PASSWORD = "PASSWORD";
    public static final String STORE_DIVISION_ID = "STORE_DIVISION_ID";
    public static final String STORE_LOCATION_ID = "STORE_LOCATION_ID";
    public static final String IS_MULTIPLE_PCL_OS_TROLLEYS = "IS_MULTIPLE_PCL_OS_TROLLEYS";
    public static final String ITEM_UPC = "ITEM_UPC";
    public static final String NON_PCL_IS_OOS_SHORT = "NON_PCL_IS_OOS_SHORT";
    public static final String FULFILLMENT_TYPE = "FULFILLMENT_TYPE";
    public static final String DYB_LARGE_ORDER = "DYB_LARGE_ORDER";
    public static final String IS_ALL_UPCS_AND_TEMP_TYPES = "IS_ALL_UPCS_AND_TEMP_TYPES";
    public static final String ITEM_QUANTITY = "ITEM_QUANTITY";
    public static final String ITEM_TEMPERATURE = "ITEM_TEMPERATURE";
    public static final String IS_RANDOM_WEIGHT = "IS_RANDOM_WEIGHT";
    public static final String IS_PARTIAL_FULFILL = "IS_PARTIAL_FULFILL ";
    public static final String ITEM_WEIGHT = "ITEM_WEIGHT";
    public static final String SHEET_NAME_TEST_DATA = "TEST_DATA";
    public static final String AMOUNT_PROCESSED = "AMOUNT_PROCESSED";
    public static final String ORDER_SOURCE = "ORDER_SOURCE";
    public static final String CUSTOMER_NAME = "CUSTOMER_NAME";
    public static final String VISUAL_ORDER_ID = "VISUAL_ORDER_ID";
    public static final String SC_ITEMS_MT_SCALE = "SC_ITEMS_MT_SCALE";
    public static final String CONTAINER_MAP = "CONTAINER_MAP";
    public static final String DELETED_CONTAINER_KEY = "DELETED_CONTAINER_KEY";
    public static final String DELETED_CONTAINER_VALUE = "DELETED_CONTAINER_VALUE";
    public static final String MULTI_CONTAINER_MAP_WITH_NR_ITEM = "MULTI_CONTAINER_MAP_WITH_NR_ITEM";
    public static final String PCL_LABEL_TROLLEY_MAP = "PCL_LABEL_TROLLEY_MAP";
    public static final String UPDATED_PCL_VALUE = "UPDATED_PCL_VALUE";
    public static final String NOT_PICKED_CONTAINER_MAP = "NOT_PICKED_CONTAINER_MAP";
    public static final String PCL_LABEL_TEMPERATURE_MAP = "PCL_LABEL_TEMPERATURE_MAP";
    public static final String CANCEL_TROLLEY_PCL_LABEL_TEMPERATURE_MAP = "CANCEL_TROLLEY_PCL_LABEL_TEMPERATURE_MAP";
    public static final String CANCEL_FROM_CIAO = "CANCEL_FROM_CIAO";
    public static final String PCL_ID_TEMPERATURE_MAP = "PCL_ID_TEMPERATURE_MAP";
    public static final String CANCEL_TROLLEY_PCL_ID_TEMPERATURE_MAP = "CANCEL_TROLLEY_PCL_ID_TEMPERATURE_MAP";
    public static final String FLEX_TROLLEY_TEMPERATURE_MAP = "FLEX_TROLLEY_TEMPERATURE_MAP";
    public static final String OVER_SIZED_CONTAINER = "OVER_SIZED_CONTAINER";
    public static final String MOVED_OS_ITEM = "MOVED_OS_ITEM";
    public static final String SALES_TAX = "SALES_TAX";
    public static final String FEE = "FEE";
    public static final String SNAP_EBT_TOTAL = "SNAP_EBT_TOTAL";
    public static final String ESTIMATED_SUBTOTAL = "ESTIMATED_SUBTOTAL";
    public static final String NON_SNAP_EBT_TOTAL = "NON_SNAP_EBT_TOTAL";
    public static final String ORDER_TOTAL = "ORDER_TOTAL";
    public static final String SHEET_NAME_ITEM_UPC_DATA = "ITEM_UPC_DATA";
    public static final String STORE_NAME = "STORE_NAME";
    public static final String POSTAL_CODE = "POSTAL_CODE";
    public static final String AGE_RESTRICTED_DOB_MONTH = "AGE_RESTRICTED_DOB_MONTH";
    public static final String AGE_RESTRICTED_DOB_DAY = "AGE_RESTRICTED_DOB_DAY";
    public static final String AGE_RESTRICTED_DOB_YEAR = "AGE_RESTRICTED_DOB_YEAR";
    public static final String PHONE_NUMBER = "PHONE_NUMBER";
    public static final String SPOT = "SPOT";
    public static final String LOYALTY_ID = "LOYALTY_ID";
    public static final String LAST_NAME = "LAST_NAME";
    public static final String FIRST_NAME = "FIRST_NAME";
    public static final String CIAO_COUPON_AMOUNT = "CIAO_COUPON_AMOUNT";
    public static final String CHECKOUT_VERSION = "CHECKOUT_VERSION";
    public static final String CITY_TOWN = "CITY_TOWN";
    public static final String STATE_PROVINCE = "STATE_PROVINCE";
    public static final String COUNTRY_CODE = "COUNTRY_CODE";
    public static final String ADDRESS_LINE1 = "ADDRESS_LINE1";
    public static final String ADDRESS_LINE2 = "ADDRESS_LINE2";
    public static final String FACILITY_ID = "FACILITY_ID";
    public static final String IS_RUSH_ORDER = "IS_RUSH_ORDER";
    public static final String MAFP_PACKAGE_COUNT = "MAFP_PACKAGE_COUNT";
    public static final String PRE_WEIGH_PKG_COUNT = "PRE_WEIGH_PKG_COUNT";
    public static final String CUE_URL = "CUE_URL";
    public static final String CODE = "CODE";
    public static final String COST_ID = "COST_ID";
    public static final String DEPARTMENT_CODE = "DEPARTMENT_CODE";
    public static final String DEPARTMENT_NAME = "DEPARTMENT_NAME";
    public static final String COMMODITY_NAME = "COMMODITY_NAME";
    public static final String COMMODITY_CODE = "COMMODITY_CODE";
    public static final String SUB_COMMODITY_CODE = "SUB_COMMODITY_CODE";
    public static final String SUB_COMMODITY_NAME = "SUB_COMMODITY_NAME";
    public static final String PRODUCT_ID = "PRODUCT_ID";
    public static final String IS_ALCOHOL = "isALCOHOL";
    public static final String AVERAGE_WEIGHT_PER_UNIT = "AVERAGE_WEIGHT_PER_UNIT";
    public static final String CUSTOMER_FACING_SIZE = "CUSTOMER_FACING_SIZE";
    public static final String KROGER_OWNED_DESCRIPTION = "KROGER_OWNED_DESCRIPTION";
    public static final String TYPE = "TYPE";
    public static final String VAULT_ID = "VAULT_ID";
    public static final String SUB_TYPE = "SUB_TYPE";
    public static final String LAST_FOUR_OF_CARD = "LAST_FOUR_OF_CARD";
    public static final String DAYS_FROM_TODAY = "DAYS_FROM_TODAY";
    public static final String IS_DELIVERY_ORDER = "IS_DELIVERY_ORDER";
    public static final String MULTIPLE_ORDER_COUNT = "MULTIPLE_ORDER_COUNT";
    public static final String MULTIPLE_ORDER_CANCEL_SCENARIO = "MULTIPLE_ORDER_CANCEL_SCENARIO";
    public static final String ITEM_MOVEMENT = "ITEM_MOVEMENT";
    public static final String CROSS_TEMP_ITEM_MOVEMENT = "CROSS_TEMP_ITEM_MOVEMENT";
    public static final String ITEMS_TO_MOVE = "ITEMS_TO_MOVE";
    public static final String MOVEMENT_FROM_CONTAINER = "MOVEMENT_FROM_CONTAINER";
    public static final String MOVEMENT_TO_CONTAINER = "MOVEMENT_TO_CONTAINER";
    public static final String ALL = "ALL";
    public static final String OS_ITEM_MOVEMENT = "OS_ITEM_MOVEMENT";
    public static final String EXISTING = "EXISTING";
    public static final String TYPE_OF_CONTAINER = "TYPE_OF_CONTAINER";
    public static final String NEW = "NEW";
    public static final String OVERSIZE = "OVERSIZE";
    public static final String FROZEN = "FROZEN";
    public static final String ITEM_MOVEMENT_VIA_SCREEN = "ITEM_MOVEMENT_VIA_SCREEN";
    public static final String ITEM_MOVEMENT_MAP = "ITEM_MOVEMENT_MAP";
    public static final String STAGING = "STAGING";
    public static final String PICKING = "PICKING";
    public static final String ORDER_LOOKUP = "ORDER_LOOKUP";
    public static final String IS_BULK_STAGING = "IS_BULK_STAGING";
    public static final String UPDATED_STAGING_ZONE_MAP = "UPDATED_STAGING_ZONE_MAP";
    public static final String CONTAINER_STATUS_MAP = "CONTAINER_STATUS_MAP";
    public static final String IS_REJECTED_ITEMS_MULTIPLE_CONTAINER = "IS_REJECTED_ITEMS_MULTIPLE_CONTAINER";
    public static final String IS_RE_STAGE = "IS_RE_STAGE";
    public static final String IS_RE_STAGE_BEFORE_ITEM_MOVEMENT = "IS_RE_STAGE_BEFORE_ITEM_MOVEMENT";
    public static final String FIRST_ORDER = "FIRST_ORDER";
    public static final String SECOND_ORDER = "SECOND_ORDER";
    public static final String LAST_ORDER = "LAST_ORDER";
    public static final String ORDER_CONFIRMATION_URL = "ORDER_CONFIRMATION_URL";
    public static final String NOT_READY_CONTAINER = "NOT_READY_CONTAINER";
    public static final String BULK_STAGING_CONTAINER_MAP = "BULK_STAGING_CONTAINER_MAP";
    public static final String SCENARIO_1 = "SCENARIO_1";
    public static final String BULK_STAGING_TC_11753 = "BULK_STAGING_TC_11753";
    public static final String BULK_STAGING_TC_11729 = "BULK_STAGING_TC_11729";
    public static final String BULK_STAGING_TC_11713 = "BULK_STAGING_TC_11713";
    public static final String BULK_STAGING_TC_11713_1 = "BULK_STAGING_TC_11713_1";
    public static final String BULK_STAGING_TC_11749 = "BULK_STAGING_TC_11749";
    public static final String BULK_STAGING_TC_11785 = "BULK_STAGING_TC_11785";
    public static final String BULK_STAGING_TC_11754 = "BULK_STAGING_TC_11754";
    public static final String BULK_STAGING_TC_11744 = "BULK_STAGING_TC_11744";
    public static final String BULK_STAGING_TC_11733 = "BULK_STAGING_TC_11733";
    public static final String BULK_STAGING_TC_11726 = "BULK_STAGING_TC_11726";
    public static final String BULK_STAGING_TC_11714 = "BULK_STAGING_TC_11714";
    public static final String BULK_STAGING_TC_11775 = "BULK_STAGING_TC_11775";
    public static final String BULK_STAGING_TC_11725 = "BULK_STAGING_TC_11725";
    public static final String BULK_STAGING_TC_11715 = "BULK_STAGING_TC_11715";
    public static final String BULK_STAGING_TC_11751 = "BULK_STAGING_TC_11751";
    public static final String BULK_STAGING_TC_11745 = "BULK_STAGING_TC_11745";
    public static final String STAGING_ZONES = "STAGING_ZONES";
    public static final String OS_STAGING_ZONE = "OS_STAGING_ZONE";
    public static final String SC_INTEGRATION_TC_14431 = "SC_INTEGRATION_TC_14431";
    public static final String PCL_SCENARIO_TC_4564 = "PCL_SCENARIO_TC_4564";
    public static final String DB_WEIGHTED_TC_13139 = "DB_WEIGHTED_TC_13139";
    public static final String DB_WEIGHTED_TC_13139_1 = "DB_WEIGHTED_TC_13139_1";
    public static final String PCL_SCENARIO_TC_4511 = "PCL_SCENARIO_TC_4511";
    public static final String PCL_SCENARIO_TC_4551 = "PCL_SCENARIO_TC_4551";
    public static final String PCL_SCENARIO_TC_4551_1 = "PCL_SCENARIO_TC_4551_1";
    public static final String PCL_SCENARIO_TC_4504 = "PCL_SCENARIO_TC_4504";
    public static final String PCL_SCENARIO_PREWEIGHED_TC_4504 = "PCL_SCENARIO_PREWEIGHED_TC_4504";
    public static final String PCL_SCENARIO_TC_4477 = "PCL_SCENARIO_TC_4477";
    public static final String PCL_SCENARIO_TC_4565 = "PCL_SCENARIO_TC_4565";
    public static final String PCL_SCENARIO_TC_4544 = "PCL_SCENARIO_TC_4544";
    public static final String PCL_SCENARIO_TC_4545 = "PCL_SCENARIO_TC_4545";
    public static final String PCL_SCENARIO_TC_4481 = "PCL_SCENARIO_TC_4481";
    public static final String PCL_SCENARIO_TC_12816 = "PCL_SCENARIO_TC_12816";
    public static final String PCL_SCENARIO_TC_4506 = "PCL_SCENARIO_TC_4506";
    public static final String PCL_SCENARIO_TC_5494 = "PCL_SCENARIO_TC_5494";
    public static final String PCL_SCENARIO_TC_4528 = "PCL_SCENARIO_TC_4528";
    public static final String PCL_SCENARIO_TC_4527 = "PCL_SCENARIO_TC_4527";
    public static final String PCL_SCENARIO_TC_4552 = "PCL_SCENARIO_TC_4552";
    public static final String PCL_SCENARIO_TC_4550 = "PCL_SCENARIO_TC_4550";
    public static final String PCL_SCENARIO_TC_4567 = "PCL_SCENARIO_TC_4567";
    public static final String PCL_SCENARIO_TC_4505 = "PCL_SCENARIO_TC_4505";
    public static final String PCL_FULFILLMENT_TYPES_SMOKE = "PCL_FULFILLMENT_TYPES_SMOKE";
    public static final String NON_PCL_FULFILLMENT_TYPES_SMOKE = "NON_PCL_FULFILLMENT_TYPES_SMOKE";
    public static final String FLEX_SCENARIO_TC_2866 = "FLEX_SCENARIO_TC_2866";
    public static final String FLEX_SCENARIO_TC_4863 = "FLEX_SCENARIO_TC_4863";
    public static final String FLEX_SCENARIO_TC_4873 = "FLEX_SCENARIO_TC_4873";
    public static final String FLEX_SCENARIO_TC_4867 = "FLEX_SCENARIO_TC_4867";
    public static final String IS_FLEX_SCENARIO = "IS_FLEX_SCENARIO";
    public static final String IS_PULL_AHEAD_FLOW = "IS_PULL_AHEAD_FLOW";
    public static final String PULL_AHEAD_FLOW_ORDER_SLOT = "PULL_AHEAD_FLOW_ORDER_SLOT";
    public static final String IS_END_JOB_EARLY = "IS_END_JOB_EARLY";
    public static final String PCL_SCENARIO_TC_4560 = "PCL_SCENARIO_TC_4560";
    public static final String PCL_SCENARIO_TC_4556 = "PCL_SCENARIO_TC_4556";
    public static final String PCL_SCENARIO_TC_4566 = "PCL_SCENARIO_TC_4566";
    public static final String PCL_SCENARIO_TC_4566_1 = "PCL_SCENARIO_TC_4566_1";
    public static final String PCL_SCENARIO_TC_5488 = "PCL_SCENARIO_TC_5488";
    public static final String PCL_SCENARIO_TC_4512 = "PCL_SCENARIO_TC_4512";
    public static final String DYNAMIC_BATCH_TC_5581 = "DYNAMIC_BATCH_TC_5581";
    public static final String ITEM_MOVEMENT_AFTER_STAGING = "ITEM_MOVEMENT_AFTER_STAGING";
    public static final String ITEM_MOVEMENT_OOS_PICKED_ITEMS = "ITEM_MOVEMENT_OOS_PICKED_ITEMS";
    public static final String IS_SINGLE_THREAD = "IS_SINGLE_THREAD";
    public static final String SCENARIO_2 = "SCENARIO_2";
    public static final String SCENARIO_3 = "SCENARIO_3";
    public static final String SCENARIO_4 = "SCENARIO_4";
    public static final String SCENARIO_5 = "SCENARIO_5";
    public static final String SCENARIO_6_1 = "SCENARIO_6_1";
    public static final String SCENARIO_6_2 = "SCENARIO_6_2";
    public static final String SCENARIO_7 = "SCENARIO_7";
    public static final String SCENARIO_8 = "SCENARIO_8";
    public static final String SCENARIO_12 = "SCENARIO_12";
    public static final String SCENARIO_13 = "SCENARIO_13";
    public static final String SCENARIO_9 = "SCENARIO_9";
    public static final String SCENARIO_10 = "SCENARIO_10";
    public static final String SCENARIO_11 = "SCENARIO_11";
    public static final String SCENARIO_11_1 = "SCENARIO_11_1";
    public static final String SCENARIO_11_1_1 = "SCENARIO_11_1_1";
    public static final String DYNAMIC_BATCH_TC_5579 = "DYNAMIC_BATCH_TC_5579";
    public static final String DYNAMIC_BATCH_TC_5578 = "DYNAMIC_BATCH_TC_5578";
    public static final String DYNAMIC_BATCH_TC_5580 = "DYNAMIC_BATCH_TC_5580";
    public static final String DYNAMIC_BATCH_TC_5575 = "DYNAMIC_BATCH_TC_5575";
    public static final String DYNAMIC_BATCH_TC_5575_1 = "DYNAMIC_BATCH_TC_5575_1";
    public static final String DYNAMIC_BATCH_TC_5578_1 = "DYNAMIC_BATCH_TC_5578_1";
    public static final String DYNAMIC_BATCH_TC_5580_1 = "DYNAMIC_BATCH_TC_5580_1";
    public static final String DYNAMIC_BATCH_TC_5575_1_1 = "DYNAMIC_BATCH_TC_5575_1_1";
    public static final String EB_NON_PCL_TC_10938 = "EB_NON_PCL_TC_10938";
    public static final String EB_NON_PCL_TC_10938_1 = "EB_NON_PCL_TC_10938_1";
    public static final String EB_NON_PCL_TC_10938_1_1 = "EB_NON_PCL_TC_10938_1_1";
    public static final String DYNAMIC_BATCH_TC_5576 = "DYNAMIC_BATCH_TC_5576";
    public static final String DYNAMIC_BATCH_TC_5576_1 = "DYNAMIC_BATCH_TC_5576_1";
    public static final String DYNAMIC_BATCH_TC_9845 = "DYNAMIC_BATCH_TC_9845";
    public static final String DYNAMIC_BATCH_TC_9845_1 = "DYNAMIC_BATCH_TC_9845_1";
    public static final String DYNAMIC_BATCH_TC_5577 = "DYNAMIC_BATCH_TC_5577";
    public static final String DYNAMIC_BATCH_TC_5577_1 = "DYNAMIC_BATCH_TC_5577_1";
    public static final String DYNAMIC_BATCH_IM_PCL_TC_9497 = "DYNAMIC_BATCH_IM_PCL_TC_9497";
    public static final String DYNAMIC_BATCH_IM_PCL_TC_9515 = "DYNAMIC_BATCH_IM_PCL_TC_9515";
    public static final String DYNAMIC_BATCH_PCL_TC_9498 = "DYNAMIC_BATCH_PCL_TC_9498";
    public static final String DYNAMIC_BATCH_OS_TC_13625 = "DYNAMIC_BATCH_OS_TC_13625";
    public static final String DYNAMIC_BATCH_OS_TC_13618 = "DYNAMIC_BATCH_OS_TC_13618";
    public static final String DYNAMIC_BATCH_OS_TC_13625_1 = "DYNAMIC_BATCH_OS_TC_13625_1";
    public static final String HARRIS_TEETER_DYB_14380 = "HARRIS_TEETER_DYB_14380";
    public static final String HARRIS_TEETER_DYB_14370 = "HARRIS_TEETER_DYB_14370";
    public static final String EB_PCL_TC_10944 = "EB_PCL_TC_10944";
    public static final String EB_PCL_TC_10944_1 = "EB_PCL_TC_10944_1";
    public static final String EB_PCL_TC_10949 = "EB_PCL_TC_10949";
    public static final String EB_PCL_TC_10949_1 = "EB_PCL_TC_10949_1";
    public static final String EB_NON_PCL_TC_10939 = "EB_NON_PCL_TC_10939";
    public static final String EB_NON_PCL_TC_10939_1 = "EB_NON_PCL_TC_10939_1";
    public static final String EB_PCL_TC_10942 = "EB_PCL_TC_10942";
    public static final String EB_PCL_TC_10942_1 = "EB_PCL_TC_10942_1";
    public static final String DYNAMIC_BATCH_PCL_TC_9499_1 = "DYNAMIC_BATCH_PCL_TC_9499_1";
    public static final String DYNAMIC_BATCH_IM_PCL_TC_9499 = "DYNAMIC_BATCH_IM_PCL_TC_9499";
    public static final String DYNAMIC_BATCH_IM_PCL_TC_9513 = "DYNAMIC_BATCH_IM_PCL_TC_9513";
    public static final String DYNAMIC_BATCH_IM_PCL_TC_9514 = "DYNAMIC_BATCH_IM_PCL_TC_9514";
    public static final String DYNAMIC_BATCH_PCL_TC_9514 = "DYNAMIC_BATCH_PCL_TC_9514";
    public static final String DYNAMIC_BATCH_PCL_TC_9514_1 = "DYNAMIC_BATCH_PCL_TC_9514_1";
    public static final String DYNAMIC_BATCH_PCL_TC_9515 = "DYNAMIC_BATCH_PCL_TC_9515";
    public static final String DYNAMIC_BATCH_PCL_TC_9515_1 = "DYNAMIC_BATCH_PCL_TC_9515_1";
    public static final String DYNAMIC_BATCH_PCL_MODIFY_9497 = "DYNAMIC_BATCH_PCL_MODIFY_9497";
    public static final String DYNAMIC_BATCH_PCL_MODIFY_9497_1 = "DYNAMIC_BATCH_PCL_MODIFY_9497_1";
    public static final String DB_PCL_MODIFY_9497_1_1 = "DB_PCL_MODIFY_9497_1_1";
    public static final String DYNAMIC_BATCH_PCL_TC_9516 = "DYNAMIC_BATCH_PCL_TC_9516";
    public static final String DB_PCL_TC_MULTIPLE_9516 = "DB_PCL_TC_MULTIPLE_9516";
    public static final String DB_PCL_TC_MULTIPLE_9516_1 = "DB_PCL_TC_MULTIPLE_9516_1";
    public static final String DB_PCL_TC_MULTIPLE_9516_1_1 = "DB_PCL_TC_MULTIPLE_9516_1_1";
    public static final String DYNAMIC_BATCH_TC_9853 = "DYNAMIC_BATCH_TC_9853";
    public static final String DYNAMIC_BATCH_PCL_TC_9854 = "DYNAMIC_BATCH_PCL_TC_9854";
    public static final String SCENARIO = "SCENARIO";
    public static final String REJECTED_ITEM_CONTAINER = "REJECTED_ITEM_CONTAINER";
    public static final String TEST_DATA_PATH = "./src/test/resources/input-data/TestData.xlsx";
    public static final String IS_COMPOSITE_PICKUP_ORDER = "IS_COMPOSITE_PICKUP_ORDER";
    public static final String CARRY_OVER_TAKE_OVER = "CARRY_OVER_TAKE_OVER";
    public static final String IS_COMPOSITE_MODIFY_ORDER = "IS_COMPOSITE_MODIFY_ORDER";
    public static final String MODIFY_SCENARIO_NAME = "MODIFY_SCENARIO_NAME";
    public static final String IS_PCL_ORDER = "IS_PCL_ORDER";
    public static final String IS_CARRYOVER_ORDER_WITHOUT_PICKING = "IS_CARRYOVER_ORDER_WITHOUT_PICKING";
    public static final String IS_NOT_READY_SCENARIO = "IS_NOT_READY_SCENARIO";
    public static final String IS_REUSE_PCL_SCENARIO = "IS_REUSE_PCL_SCENARIO";
    public static final String IS_OOS_SHORT = "IS_OOS_SHORT";
    public static final String TROLLEYS = "TROLLEYS";
    public static final String PCL_SCENARIO_TC_4561 = "PCL_SCENARIO_TC_4561";
    public static final String PCL_SCENARIO_TC_4561_1 = "PCL_SCENARIO_TC_4561_1";
    public static final String PCL_SCENARIO_TC_4561_1_1 = "PCL_SCENARIO_TC_4561_1_1";
    public static final String DB_EXPRESS_ORDER_TC_14041 = "DB_EXPRESS_ORDER_TC_14041";
    public static final String DB_EXPRESS_ORDER_TC_14041_1 = "DB_EXPRESS_ORDER_TC_14041_1";
    public static final String DB_EXPRESS_ORDER_TC_14041_1_1 = "DB_EXPRESS_ORDER_TC_14041_1_1";
    public static final String MULTI_UPC_CONTAINER = "MULTI_UPC_CONTAINER";
    public static final String MULTI_CONTAINER_TROLLEY = "MULTI_CONTAINER_TROLLEY";
    public static final String MULTI_UPC_CONTAINER_PCL_VALUES = "MULTI_UPC_CONTAINER_PCL_VALUES";
    public static final String MULTI_UPC_CONTAINER_VALUES = "MULTI_UPC_CONTAINER_VALUES";
    public static final String PCL_SCENARIO_TC_4563 = "PCL_SCENARIO_TC_4563";
    public static final String PCL_SCENARIO_TC_4563_1 = "PCL_SCENARIO_TC_4563_1";
    public static final String PCL_SCENARIO_TC_4563_1_1 = "PCL_SCENARIO_TC_4563_1_1";
    public static final String PCL_SCENARIO_TC_5504 = "PCL_SCENARIO_TC_5504";
    public static final String PCL_SCENARIO_TC_5762 = "PCL_SCENARIO_TC_5762";
    public static final String PCL_SCENARIO_TC_5505 = "PCL_SCENARIO_TC_5505";
    public static final String FROM_CONTAINER_STATUS = "FROM_CONTAINER_STATUS";
    public static final String TO_CONTAINER_STATUS = "TO_CONTAINER_STATUS";
    public static final String IS_PICK_TO_BAG = "IS_PICK_TO_BAG";
    public static final String IS_ANCHOR_STAGING_ZONE = "IS_ANCHOR_STAGING_ZONE";
    public static final String IS_DB_PCL_SINGLE_THREAD = "IS_DB_PCL_SINGLE_THREAD";
    public static final String STAGED = "STAGED";
    public static final String PCL_SCENARIO_TC_4507 = "PCL_SCENARIO_TC_4507";
    public static final String SOME = "SOME";
    public static final String PCL_SCENARIO_TC_4568 = "PCL_SCENARIO_TC_4568";
    public static final String PCL_OVERSIZE_SCENARIO_TC_4568 = "PCL_OVERSIZE_SCENARIO_TC_4568";
    public static final String PCL_SCENARIO_TC_4539 = "PCL_SCENARIO_TC_4539";
    public static final String IS_TAKE_OVER_TROLLEY = "IS_TAKE_OVER_TROLLEY";
    public static final String TAKE_OVER_TROLLEY = "TAKE_OVER_TROLLEY";
    public static final String TAKE_OVER_CONTAINER_NO = "TAKE_OVER_CONTAINER_NO";
    public static final String AMBIENT = "AMBIENT";
    public static final String REFRIGERATED = "REFRIGERATED";
    public static final String DE_METER_PICKING_MAP = "DE_METER_PICKING_MAP";
    public static final String DE_METER_CONTAINER_MAP = "DE_METER_CONTAINER_MAP";
    public static final String MOVEMENT_TO_OOS = "MOVEMENT_TO_OOS";
    public static final String RUSH_ORDER_SCENARIO_TC_7140 = "RUSH_ORDER_SCENARIO_TC_7140";
    public static final String RUSH_ORDER_SCENARIO_TC_7140_1 = "RUSH_ORDER_SCENARIO_TC_7140_1";
    public static final String RUSH_ORDER_SCENARIO_TC_7140_2 = "RUSH_ORDER_SCENARIO_TC_7140_2";
    public static final String RUSH_ORDER_SCENARIO_TC_7131 = "RUSH_ORDER_SCENARIO_TC_7131";
    public static final String RUSH_ORDER_SCENARIO_TC_7131_1 = "RUSH_ORDER_SCENARIO_TC_7131_1";
    public static final String RUSH_ORDER_SCENARIO_TC_7131_2 = "RUSH_ORDER_SCENARIO_TC_7131_2";
    public static final String RUSH_ORDER_SCENARIO_TC_7140_3 = "RUSH_ORDER_SCENARIO_TC_7140_3";
    public static final String RUSH_ORDER_SCENARIO_TC_6706 = "RUSH_ORDER_SCENARIO_TC_6706";
    public static final String ROMB_SCENARIO_TC_7122 = "ROMB_SCENARIO_TC_7122";
    public static final String ROMB_SCENARIO_TC_7122_1 = "ROMB_SCENARIO_TC_7122_1";
    public static final String ROMB_SCENARIO_TC_7122_2 = "ROMB_SCENARIO_TC_7122_2";
    public static final String RUSH_ORDER_SCENARIO_TC_6696 = "RUSH_ORDER_SCENARIO_TC_6696";
    public static final String RUSH_ORDER_SCENARIO_TC_6559 = "RUSH_ORDER_SCENARIO_TC_6559";
    public static final String RUSH_ORDER_SCENARIO_TC_6693 = "RUSH_ORDER_SCENARIO_TC_6693";
    public static final String RUSH_ORDER_SCENARIO_TC_6685 = "RUSH_ORDER_SCENARIO_TC_6685";
    public static final String RUSH_ORDER_SCENARIO_TC_6685_1 = "RUSH_ORDER_SCENARIO_TC_6685_1";
    public static final String RUSH_ORDER_SCENARIO_TC_7120 = "RUSH_ORDER_SCENARIO_TC_7120";
    public static final String RUSH_ORDER_SCENARIO_TC_7120_1 = "RUSH_ORDER_SCENARIO_TC_7120_1";
    public static final String TC_52_NOTIFICATION_TC_7035 = "TC_52_NOTIFICATION_TC_7035";
    public static final String TC_52_NOTIFICATION_TC_7038 = "TC_52_NOTIFICATION_TC_7038";
    public static final String TC_52_NOTIFICATION_TC_7038_1 = "TC_52_NOTIFICATION_TC_7038_1";
    public static final String INSTACART_SCENARIO_TC_12864 = "INSTACART_SCENARIO_TC_12864";
    public static final String INSTACART_SCENARIO_TC_12846 = "INSTACART_SCENARIO_TC_12846";
    public static final String INSTACART_SCENARIO_TC_12963 = "INSTACART_SCENARIO_TC_12963";
    public static final String INSTACART_SCENARIO_TC_12963_1 = "INSTACART_SCENARIO_TC_12963_1";
    public static final String ANCHOR_SCENARIO_TC_5309 = "ANCHOR_SCENARIO_TC_5309";
    public static final String RUSH_ORDER_SCENARIO_TC_7114 = "RUSH_ORDER_SCENARIO_TC_7114";
    public static final String RUSH_ORDER_TC52_TC_7114 = "RUSH_ORDER_TC52_TC_7114";
    public static final String PICKUP_TIME = "PICKUP_TIME";
    public static final String DYNAMIC_BATCH_PCL_MODIFY_9844 = "DYNAMIC_BATCH_PCL_MODIFY_9844";
    public static final String DYNAMIC_BATCH_PCL_MODIFY_9844_1 = "DYNAMIC_BATCH_PCL_MODIFY_9844_1";
    public static final String DB_PCL_MODIFY_9844_1_1 = "DB_PCL_MODIFY_9844_1_1";
    public static final String BULK_STAGING_TC_11723_ANCHOR = "BULK_STAGING_TC_11723_ANCHOR";
    public static final String DYNAMIC_BATCH_PCL_TC_9857 = "DYNAMIC_BATCH_PCL_TC_9857";
    public static final String DYNAMIC_BATCH_PCL_TC_9857_1 = "DYNAMIC_BATCH_PCL_TC_9857_1";
    public static final String IS_SINGLE_ORDER_LEVEL_BATCH = "IS_SINGLE_ORDER_LEVEL_BATCH";
    public static final String IS_PCL_SINGLE_THREAD_CARRYOVER = "IS_PCL_SINGLE_THREAD_CARRYOVER";
    public static final String SELL_BY_UNIT = "SELL_BY_UNIT";
    public static final String SELL_BY = "Unit";
    public static final String SELL_BY_WEIGHT_ITEM = "SELL_BY_WEIGHT_ITEM";
    public static final String IS_MAFP = "IS_MAFP";
    public static final String BULK_STAGING_TC_11728 = "BULK_STAGING_TC_11728";
    public static final String BULK_STAGING_TC_11728_1 = "BULK_STAGING_TC_11728_1";
    public static final String BULK_STAGING_TC_11747 = "BULK_STAGING_TC_11747";
    public static final String MAFP_NOT_READY_FOR_ORDER_ADJUSTMENT_UNIT = "MAFP_NOT_READY_FOR_ORDER_ADJUSTMENT_UNIT";
    public static final String MAFP_PACKAGE_COUNT_SELL_BY_UNIT = "MAFP_PACKAGE_COUNT_SELL_BY_UNIT";
    public static final String MAFP_CIAO_SCENARIO_TC_10448 = "MAFP_CIAO_SCENARIO_TC_10448";
    public static final String CIAO_SUBSTITUTE_ITEM_REJECT = "CIAO_SUBSTITUTE_ITEM_REJECT";
    public static final String CIAO_SUBSTITUTE_ITEM_ACCEPT = "CIAO_SUBSTITUTE_ITEM_ACCEPT";
    public static final String BULK_STAGING_TC_11786 = "BULK_STAGING_TC_11786";
    public static final String TROLLEY_COUNT = "TROLLEY_COUNT";
    public static final String TROLLEY_CONTAINERS = "TROLLEY_CONTAINERS";
    public static final String COMMON_TROLLEY_CANCEL = "COMMON_TROLLEY_CANCEL";
    public static final String MAFP_CIAO_SCENARIO_TC_10458 = "MAFP_CIAO_SCENARIO_TC_10458";
    public static final String INFORMATION_LOOKUP = "INFORMATION_LOOKUP";
    public static final String ITEM_MOVEMENT_TYPE = "ITEM_MOVEMENT_TYPE";
    public static final String PCL_LABEL = "PCL_LABEL";
    public static final String STAGING_LOCATION = "STAGING_LOCATION";
    public static final String MULTIPLE_OS_UPC_TEMP = "MULTIPLE_OS_UPC_TEMP";
    public static final String MAFP_CIAO_SCENARIO_TC_10442 = "MAFP_CIAO_SCENARIO_TC_10442";
    public static final String BULK_STAGING_TC_11776 = "BULK_STAGING_TC_11776";
    public static final String PCL_OVERSIZE_TC_12050 = "PCL_OVERSIZE_TC_12050";
    public static final String PCL_OVERSIZE_TC_12224 = "PCL_OVERSIZE_TC_12224";
    public static final String PCL_OVERSIZE_TC_12169 = "PCL_OVERSIZE_TC_12169";
    public static final String PCL_OVERSIZE_TC_12223 = "PCL_OVERSIZE_TC_12223";
    public static final String IS_TAKEOVER_WITHOUT_CARRYOVER = "IS_TAKEOVER_WITHOUT_CARRYOVER";
    public static final String PCL_OVERSIZE_TC_12131 = "PCL_OVERSIZE_TC_12131";
    public static final String PCL_OVERSIZE_TC_12131_1 = "PCL_OVERSIZE_TC_12131_1";
    public static final String PCL_OVERSIZE_TC_12134 = "PCL_OVERSIZE_TC_12134";
    public static final String PCL_OVERSIZE_TC_12165 = "PCL_OVERSIZE_TC_12165";
    public static final String PCL_OVERSIZE_TC_12165_1 = "PCL_OVERSIZE_TC_12165_1";
    public static final String PCL_OVERSIZE_TC_12165_1_1 = "PCL_OVERSIZE_TC_12165_1_1";
    public static final String PCL_OVERSIZE_TC_12089 = "PCL_OVERSIZE_TC_12089";
    public static final String PCL_OVERSIZE_TC_12089_1 = "PCL_OVERSIZE_TC_12089_1";
    public static final String PCL_OVERSIZE_TC_12148_1 = "PCL_OVERSIZE_TC_12148_1";
    public static final String PCL_OVERSIZE_TC_12148 = "PCL_OVERSIZE_TC_12148";
    public static final String GET_STAGING_ZONES = "GET_STAGING_ZONES";
    public static final String STAGING_STATUS = "STAGING_STATUS";
    public static final String IS_DB_OS_REUSE_PCL_SPLIT_TROLLEY = "IS_DB_OS_REUSE_PCL_SPLIT_TROLLEY";
    public static final String IS_DB_OS_REUSE_PCL_STAGING = "IS_DB_OS_REUSE_PCL_STAGING";
    public static final String DYNAMIC_BATCH_OS_TC_13629 = "DYNAMIC_BATCH_OS_TC_13629";
    public static final String PCL_OS_PROD_DEFECT_CARRYOVER = "PCL_OS_PROD_DEFECT_CARRYOVER";
    public static final String INSTACART_SCENARIO_TC_12847 = "INSTACART_SCENARIO_TC_12847";
    public static final String INSTACART_SCENARIO_TC_12962 = "INSTACART_SCENARIO_TC_12962";
    public static final String INSTACART_SCENARIO_TC_12862 = "INSTACART_SCENARIO_TC_12862";
    public static final String INSTACART_SCENARIO_TC_12862_1 = "INSTACART_SCENARIO_TC_12862_1";
    public static final String IS_EXPRESS_ORDER = "IS_EXPRESS_ORDER";
    public static final String DB_EXPRESS_ORDER_TC_14052 = "DB_EXPRESS_ORDER_TC_14052";
    public static final String DB_EXPRESS_ORDER_TC_14052_1 = "DB_EXPRESS_ORDER_TC_14052_1";
    public static final String DB_EXPRESS_ORDER_TC_14046 = "DB_EXPRESS_ORDER_TC_14046";
    public static final String DB_EXPRESS_ORDER_TC_14046_1 = "DB_EXPRESS_ORDER_TC_14046_1";
    public static final String DB_EXPRESS_ORDER_TC_14054_1 = "DB_EXPRESS_ORDER_TC_14054_1";
    public static final String DB_EXPRESS_ORDER_TC_14054 = "DB_EXPRESS_ORDER_TC_14054";
    public static final String EXPRESS_FEE = "EXPRESS_FEE";
    public static final String DB_EXPRESS_ORDER_TC_14058 = "DB_EXPRESS_ORDER_TC_14058";
    public static final String DB_EXPRESS_ORDER_TC_14058_1 = "DB_EXPRESS_ORDER_TC_14058_1";
    public static final String PCL_OVERSIZE_TC_12138 = "PCL_OVERSIZE_TC_12138";
    public static final String BYOB_TC_7453 = "BYOB_TC_7453";
    public static final String BYOB_EXPRESS_TC_9172 = "BYOB_EXPRESS_TC_9172";
    public static final String DB_EXPRESS_ORDER_TC_14050 = "DB_EXPRESS_ORDER_TC_14050";
    public static final String DB_EXPRESS_ORDER_TC_14047 = "DB_EXPRESS_ORDER_TC_14047";
    public static final String DB_EXPRESS_ORDER_TC_14047_1 = "DB_EXPRESS_ORDER_TC_14047_1";
    public static final String DYNAMIC_BATCH_OS_TC_13623 = "DYNAMIC_BATCH_OS_TC_13623";
    public static final String DYNAMIC_BATCH_OS_TC_13620 = "DYNAMIC_BATCH_OS_TC_13620";
    public static final String NOT_READY_SUBSTITUTION = "NOT_READY_SUBSTITUTION";
    public static final String BYOB_PCL_TC_7464 = "BYOB_PCL_TC_7464";
    public static final String INSTACART_SCENARIO_TC_12845 = "INSTACART_SCENARIO_TC_12845";
    public static final String BYOB_PCL_TC_9083_1 = "BYOB_PCL_TC_9083_1";
    public static final String BYOB_PCL_TC_9083 = "BYOB_PCL_TC_9083";
    public static final String DB_EXPRESS_ORDER_TC_14040 = "DB_EXPRESS_ORDER_TC_14040";
    public static final String DB_EXPRESS_ORDER_TC_14040_1 = "DB_EXPRESS_ORDER_TC_14040_1";
    public static final String DB_EXPRESS_ORDER_TC_14040_2 = "DB_EXPRESS_ORDER_TC_14040_2";
    public static final String BYOB_PCL_TC_7462 = "BYOB_PCL_TC_7462";
    public static final String BYOB_PCL_TC_9170 = "BYOB_PCL_TC_9170";
    public static final String BYOB_PCL_TC_7460 = "BYOB_PCL_TC_7460";
    public static final String DB_HT_TC_14378_1_1 = "DB_HT_TC_14378_1_1";
    public static final String DB_HT_TC_14378_1 = "DB_HT_TC_14378_1";
    public static final String DB_HT_TC_14378 = "DB_HT_TC_14378";
    public static final String DB_WEIGHTED_TROLLEY_13140 = "DB_WEIGHTED_TROLLEY_13140";
    public static final String DB_WEIGHTED_TROLLEY_13140_1 = "DB_WEIGHTED_TROLLEY_13140_1";
    public static final String ANCHOR_SCENARIO_TC_5313 = "ANCHOR_SCENARIO_TC_5313";
    public static final String ANCHOR_SCENARIO_TC_5317 = "ANCHOR_SCENARIO_TC_5317";
    public static final String ANCHOR_SCENARIO_TC_5315 = "ANCHOR_SCENARIO_TC_5315";
    public static final String ANCHOR_SCENARIO_TC_5323 = "ANCHOR_SCENARIO_TC_5323";
    public static final String COLLAPSE_AMRE_OSFR_SMOS = "COLLAPSE_AMRE_OSFR_SMOS";
    public static final String IS_SMALL_OS_ITEM_PRESENT = "IS_SMALL_OS_ITEM_PRESENT";
    public static final String ITEM_SIZE = "ITEM_SIZE";
    public static final String MAX_SMOS_COUNT = "MAX_SMOS_COUNT";
    public static final String COLLAPSE_AM_RE_OSFR_SMOS = "COLLAPSE_AM_RE_OS_FR_SMOS";
    public static final String DYNAMIC_BATCH_9TOTE_TC_15066 = "DYNAMIC_BATCH_9TOTE_TC_15066";
    public static final String DYNAMIC_BATCH_9TOTE_15081 = "DYNAMIC_BATCH_9TOTE_15081";
    public static final String DYNAMIC_BATCH_9TOTE_15081_1 = "DYNAMIC_BATCH_9TOTE_15081_1";
    public static final String IS_DB_OS_ENABLED = "IS_DB_OS_ENABLED";
    public static final String DYNAMIC_BATCH_9TOTE_TC_15068 = "DYNAMIC_BATCH_9TOTE_TC_15068";
    public static final String DYNAMIC_BATCH_9TOTE_15073 = "DYNAMIC_BATCH_9TOTE_15073";
    public static final String DYNAMIC_BATCH_9TOTE_15073_1 = "DYNAMIC_BATCH_9TOTE_15073_1";
    public static final String DYNAMIC_BATCH_9TOTE_15073_1_1 = "DYNAMIC_BATCH_9TOTE_15073_1_1";
    public static final String DYNAMIC_BATCH_9TOTE_TC_15067 = "DYNAMIC_BATCH_9TOTE_TC_15067";
    public static final String HARRIS_TEETER_DYB_14374 = "HARRIS_TEETER_DYB_14374";
    public static final String DYNAMIC_BATCH_9TOTE_TC_15083 = "DYNAMIC_BATCH_9TOTE_TC_15083";
    public static String INSTACART_ID = "INSTACART_ID";
    public static String INSTACART_CUE_VISUAL_ORDER_ID = "INSTACART_CUE_VISUAL_ORDER_ID";
    public static String INSTACART_VISUAL_ORDER_ID = "INSTACART_VISUAL_ORDER_ID";
    public static String INSTACART_CONTAINER_MAP = "INSTACART_CONTAINER_MAP";
    public static String INSTACART_PARTNER_ORDER_ID = "INSTACART_PARTNER_ORDER_ID";
    public static String IS_INSTACART_ORDER = "IS_INSTACART_ORDER";
    public static final String PCL_OS_PROD_DEFECT_MOVE_ITEMS = "PCL_OS_PROD_DEFECT_MOVE_ITEMS";
    public static final String PCL_OS_PROD_DEFECT_SAME_ITEMS = "PCL_OS_PROD_DEFECT_SAME_ITEMS";
    public static final String DB_SINGLE_THREAD_12728 = "DB_SINGLE_THREAD_12728";
    public static final String DB_SINGLE_THREAD_12728_1 = "DB_SINGLE_THREAD_12728_1";
    public static final String DB_SINGLE_THREAD_12732 = "DB_SINGLE_THREAD_12732";
    public static final String DB_SINGLE_THREAD_12761_1 = "DB_SINGLE_THREAD_12761_1";
    public static final String DB_SINGLE_THREAD_12761_2 = "DB_SINGLE_THREAD_12761_2";
    public static final String DYNAMIC_BATCH_OS_TC_13619 = "DYNAMIC_BATCH_OS_TC_13619";
    public static final String PCL_OS_DEFECT_DIFFERENT_ITEMS = "PCL_OS_DEFECT_DIFFERENT_ITEMS";
    public static final String HARRIS_TEETER_DYB_14373 = "HARRIS_TEETER_DYB_14373";
    public static final String HARRIS_TEETER_DYB_14376 = "HARRIS_TEETER_DYB_14376";
    public static final String HARRIS_TEETER_DYB_14376_1 = "HARRIS_TEETER_DYB_14376_1";
    public static final String HARRIS_TEETER_DYB_14376_1_1 = "HARRIS_TEETER_DYB_14376_1_1";
    public static final String HARRIS_TEETER_DYB_14372 = "HARRIS_TEETER_DYB_14372";
    public static final String IS_PCL_OS_DIFFERENT_UPC = "IS_PCL_OS_DIFFERENT_UPC";
    public static final String DB_SINGLE_THREAD_12730 = "DB_SINGLE_THREAD_12730";
    public static final String DYNAMIC_BATCH_OS_TC_13616 = "DYNAMIC_BATCH_OS_TC_13616";
    public static final String DYNAMIC_BATCH_OS_TC_13617 = "DYNAMIC_BATCH_OS_TC_13617";
    public static final String DYNAMIC_BATCH_OS_TC_13624 = "DYNAMIC_BATCH_OS_TC_13624";
    public static final String DYNAMIC_BATCH_OS_TC_13624_1 = "DYNAMIC_BATCH_OS_TC_13624_1";
    public static final String DYNAMIC_BATCH_OS_TC_13624_1_1 = "DYNAMIC_BATCH_OS_TC_13624_1_1";
    public static final String COURIER_SERVICES_9593 = "COURIER_SERVICES_9593";
    public static final String COURIER_SERVICES_9592 = "COURIER_SERVICES_9592";
    public static String TC_52_Notifications_7044 = "TC_52_Notifications_7044";
    public static String TC_52_NOTIFICATION_TC_9872 = "TC_52_NOTIFICATION_TC_9872";
    public static String HARRIS_TEETER_DYB_14375 = "HARRIS_TEETER_DYB_14375";
    public static String COLLAPSE_TEMPERATURE_TROLLEY_CONTAINERS = "COLLAPSE_TEMPERATURE_TROLLEY_CONTAINERS";
    public static String ENHANCED_BATCHING_MAP = "ENHANCED_BATCHING_MAP";
    public static String COLLAPSE_NONE = "COLLAPSE_NONE";
    public static String COLLAPSE_AMRE = "AMRE";
    public static String COLLAPSE_AMRE_OSFR = "OSFR & AMRE";
    public static String OSFR = "OSFR";
    public static String COLLAPSE_ALL = "COLLAPSE_ALL";
    public static String IS_PCL_OVERSIZE = "IS_PCL_OVERSIZE";
    public static String IS_STAGE_FROM_LOOKUP = "IS_STAGE_FROM_LOOKUP";
    public static String IS_PCL_OVERSIZE_TAKE_OVER_ASSIGNING = "IS_PCL_OVERSIZE_TAKE_OVER_ASSIGNING";
    public static String IS_MULTIPLE_OVERSIZE = "IS_MULTIPLE_OVERSIZE";
    public static String REQUEST_TROLLEY_FROM_HARVESTER = "REQUEST_TROLLEY_FROM_HARVESTER";

    private static ExcelUtils instance;

    private ExcelUtils() {
    }

    public static HashMap<String, String> getTestDataMap(String scenario, String SheetName) {
        HashMap<String, String> readMap = new HashMap<>();
        try {
            FileInputStream fileInput = new FileInputStream(TEST_DATA_PATH);
            Workbook workbook = WorkbookFactory.create(fileInput);
            Sheet sheet = workbook.getSheet(SheetName);
            int rowCount = 0;
            int rowHeaderIndex = 0;
            List<String> headerList = new ArrayList<>();
            Row headerRow = sheet.getRow(rowHeaderIndex);
            for (int i = 0; i < headerRow.getLastCellNum(); i++) {
                headerList.add(i, sheet.getRow(rowHeaderIndex).getCell(i).toString());
            }
            int scenarioColumnIndex = headerList.indexOf(SCENARIO);
            for (Row row : sheet) {
                if (row.getCell(scenarioColumnIndex).toString().equalsIgnoreCase(scenario)) {
                    break;
                }
                rowCount = rowCount + 1;
            }
            int columnCount = sheet.getRow(rowCount).getLastCellNum();
            for (int i = 0; i < columnCount; i++) {
                if (sheet.getRow(rowCount).getCell(i) != null) {
                    readMap.put(sheet.getRow(rowHeaderIndex).getCell(i).toString(), sheet.getRow(rowCount).getCell(i).toString());
                }
            }
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        return readMap;
    }

    public static List<HashMap<String, String>> getItemUpcData(String scenario) {
        List<HashMap<String, String>> upcList = new ArrayList<>();
        try {
            FileInputStream fileInput = new FileInputStream("./src/test/resources/input-data/TestData.xlsx");
            Workbook workbook = WorkbookFactory.create(fileInput);
            Sheet sheet = workbook.getSheet(SHEET_NAME_ITEM_UPC_DATA);
            int scenarioColumnIndex = 0;
            int rowHeaderIndex = 0;
            int rowCount = sheet.getLastRowNum();
            int columnCount = sheet.getRow(rowHeaderIndex).getLastCellNum();
            for (int j = rowCount; j > 0; j--) {
                HashMap<String, String> upcMap = new HashMap<>();
                if (sheet.getRow(j).getCell(scenarioColumnIndex).toString().equalsIgnoreCase(scenario)) {
                    for (int i = 1; i < columnCount; i++) {
                        if (sheet.getRow(j).getCell(i) != null) {
                            upcMap.put(sheet.getRow(rowHeaderIndex).getCell(i).toString(), sheet.getRow(j).getCell(i).toString());
                        }
                    }
                    upcList.add(upcMap);
                }
            }
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        return upcList;
    }

    public static void writeToExcel(String sheetName, HashMap<String, String> outputDataMap) {
        String filePath = "./src/test/resources/input-data/TestData.xlsx";
        try {
            Workbook workbook = new XSSFWorkbook(Files.newInputStream(Paths.get(filePath)));
            Sheet sheet = getSheet(sheetName, workbook);
            AtomicInteger columnCount = new AtomicInteger();
            sheet.createRow(0);
            sheet.createRow(1);
            outputDataMap.forEach((key, value) -> {
                sheet.getRow(0).createCell(columnCount.get()).setCellValue(key);
                sheet.getRow(1).createCell(columnCount.get()).setCellValue(value);
                columnCount.set(columnCount.get() + 1);
            });
            FileOutputStream outputStream = new FileOutputStream(filePath);
            workbook.write(outputStream);
            workbook.close();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    public static void removeExistingDataFromExcel(String sheetName) {
        try {
            String filePath = "./src/test/resources/input-data/TestData.xlsx";
            Workbook workbook = new XSSFWorkbook(Files.newInputStream(Paths.get(filePath)));
            int index = workbook.getSheetIndex(sheetName);
            if (index > 1) {
                workbook.removeSheetAt(index);
                FileOutputStream fileOutputStream = new FileOutputStream(filePath);
                workbook.write(fileOutputStream);
                fileOutputStream.close();
            }
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    private static Sheet getSheet(String sheetName, Workbook workbook) {
        List<String> sheetNames = new ArrayList<>(30);
        for (int i = 0; i < workbook.getNumberOfSheets(); i++) {
            sheetNames.add(workbook.getSheetName(i));
        }
        if (!sheetNames.contains(sheetName)) {
            workbook.createSheet(sheetName);
        }
        return workbook.getSheet(sheetName);
    }

    public static HashMap<String, String> convertStringToMap(String value) {
        HashMap<String, String> convertedMap = new HashMap<>();
        value = value.substring(1, value.length() - 1);
        String[] keyValuePairs = value.split(",");
        for (String pair : keyValuePairs) {
            String[] keyValue = pair.trim().split("=");
            convertedMap.put(keyValue[0], keyValue[1]);
        }
        return convertedMap;
    }

    public static List<String> convertStringToList(String value) {
        value = value.substring(1, value.length() - 1);
        value = value.replace(" ", "");
        return Arrays.asList(value.split(",", -1));
    }

    public static String getKeyValue(HashMap<String, String> testDataMap, String key) {
        String mapValue;
        try {
            mapValue = testDataMap.get(key);
        } catch (Exception e) {
            throw new RuntimeException("Unable to retrieve value for " + key + e);
        }
        return mapValue;
    }

    public synchronized ExcelUtils getInstance() {
        if (instance != null) {
            return instance;
        }
        synchronized (ExcelUtils.class) {
            if (instance == null) {
                instance = new ExcelUtils();
            }
        }
        return instance;
    }
}