name: Mobile-Grid Automation - Benchmark
on:
  workflow_dispatch:
    inputs:
      folder:
        description: "Suite Folder Name"
        required: true
        default: "smoke"
      suite:
        description: "Suite Name"
        required: true
        default: "smokeScenarios"
      wait:
        description: "wait"
        required: false
        default: "20"

env:
  ARTIFACTORY_EDGE_USERNAME_REF: ${{ secrets.ARTIFACTORY_EDGE_USERNAME }}
  ARTIFACTORY_EDGE_TOKEN_REF: ${{ secrets.ARTIFACTORY_EDGE_TOKEN }}

jobs:
  run_automation_tests:
    name: Run automation tests
    runs-on: [self-hosted,kubernetes]
    container: maven:3.8.5-openjdk-11
    steps:
      - name: checkout code
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: temurin
          overwrite-settings: true

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run automation tests with Maven
        run: >-
          mvn clean test --settings settings.xml -DsuiteFolder=${{ github.event.inputs.folder }} -Dsuite=${{ github.event.inputs.suite }}

      - name: Upload logs and extent report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Logs and Extent Reports
          path: |
            target/Logs/*
            test-output/Reports
          if-no-files-found: ignore

      - name: Publish surefire test report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1
        with:
          report_paths: "**/surefire-reports/TEST-*.xml"
