name: E2e - Regression Suite Execution
on:
  workflow_dispatch:
    inputs:
      groups:
        description: "Select the regression suite"
        required: true
        type: choice
        options:
          - enhancedDynamicBatching
          - smoke

env:
  ARTIFACTORY_EDGE_USERNAME_REF: ${{ secrets.ARTIFACTORY_EDGE_USERNAME }}
  ARTIFACTORY_EDGE_TOKEN_REF: ${{ secrets.ARTIFACTORY_EDGE_TOKEN }}
  TZ: 'America/New_York'
  HARVESTER_VERSION: '5.27.0'
  CIAO_VERSION: '3.4-debug.510'

jobs:

  Retrieve-Scripts:
    runs-on: ubuntu-latest
    outputs:
      job_list: ${{ steps.set.outputs.job_list }}
    steps:
      - id: set
        run: |
          if [ "${{ github.event.inputs.groups }}" == "enhancedDynamicBatching" ]; then
            echo 'job_list=["criticalEnhancedDyBAnchorGranularOSFRFFILLSVCS10946","criticalEnhancedDyBAzureShiptFFILLSVCS10936","criticalEnhancedDyBCancelOrderItemMovementFFILLSVCS10942","criticalEnhancedDyBCancelOrderItemMovementFFILLSVCS10942"]' >> $GITHUB_OUTPUT
          else
            echo 'job_list=["smokeTC52RombRushOrderPclE2eBauFFILLSVCS7114"]' >> $GITHUB_OUTPUT
          fi

  Execute-Scripts:
    needs: Retrieve-Scripts
    runs-on: [self-hosted, kubernetes]
    container: maven:3.8.5-openjdk-11
    strategy:
      matrix:
        suite_name: ${{ fromJson(needs.Retrieve-Scripts.outputs.job_list) }}
    name: Regression for ${{ matrix.suite_name }}

    steps:
      - name: checkout code
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: "21"
          distribution: temurin
          overwrite-settings: true

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Getting branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Run automation tests with ${{ matrix.suite_name }}.xml
        id: scenario_1
        if: ${{ ! cancelled() }}
        run: >-
          mvn clean test --settings settings.xml
          -DsuiteFolder="${{ github.event.inputs.groups }}"
          -Dsuite="${{ matrix.suite_name }}"
          -Dreportportal="true"
          -Dlaunch-name="Regression_${{ github.event.inputs.groups }}_${{ matrix.suite_name }}"
          -Dbranch=${BRANCH_NAME}
          -DHARVESTER_VERSION="${{ env.HARVESTER_VERSION }}"
          -DCIAO_VERSION="${{ env.CIAO_VERSION }}"

      - name: Upload logs and extent for ${{ matrix.suite_name }}
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Logs and Extent Reports for ${{ matrix.suite_name }}
          path: |
            target/Logs/*
            test-output/Reports
          if-no-files-found: ignore

      - name: Upload results.json
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Results json file for ${{ matrix.suite_name }}
          path: |
            src/test/resources/test-results/results.json
          if-no-files-found: ignore
          retain-on-cancel: false

      - name: Upload Surefire reports as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Surefire Reports ${{ matrix.suite_name }}
          path: target/surefire-reports/TEST-*.xml
          if-no-files-found: ignore

      - name: Publish surefire test report for ${{ matrix.suite_name }}
        if: always()
        uses: scacap/action-surefire-report@v1
        with:
          report_paths: "**/surefire-reports/TEST-*.xml"